### ISSUE TITLE
API's giving 404.

### ISSUE THREAD

**Issue by rithin** [igorbenav/FastAPI-boilerplate#120]
API's giving 404.
I build using docker-compose 

My latest code can see here-> https://github.com/rithin/kappitrails_api/tree/development_v1

**Description**
only apis are working if i wrote in the main.py but what in api/v1/users.py or any other

**Screenshots**
![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/26068dcf-15ec-4968-ac0e-706f4227d68e)

![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/b7ffd492-2e19-4820-8f01-67ed09747dea)
![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/7e5be928-7ab8-4adc-bfaf-e2e4115cec8f)

**Additional context**

**Comment by igorbenav** [comment]
Hey, @rithin, I'll take a look and get back to you as soon as possible!

**Comment by igorbenav** [comment]
Which .env type are you using? Local, Staging or Production?

**Comment by igorbenav** [comment]
Ok, found the issue. It's this bug: #117 which was fixed in #118.

All you need to do is add this part: `application.include_router(router)` in the `if isinstance(settings, EnvironmentSettings):` condition in `app/core/setup.py`

```python
if isinstance(settings, EnvironmentSettings):
    if settings.ENVIRONMENT != EnvironmentOption.PRODUCTION:
        docs_router = APIRouter()
        if settings.ENVIRONMENT != EnvironmentOption.LOCAL:
            docs_router = APIRouter(dependencies=[Depends(get_current_superuser)])
        ...
        ...
        application.include_router(docs_router)
        
        # --------------- adding this line fixes the bug ---------------
        application.include_router(router)
```

Tell me if it works for you.

**Comment by rithin** [comment]
@igorbenav Thanks for the quick reply. That was the issue and it's resolved.

 I'm getting one more issue like **create_tier** and **create_superuser** containers are creating and exiting
In user table i can see the admin entry but in tier table there is no entry. 
--------------------------------------------
**logs-create_tier**
asyncio.exceptions.CancelledError
2024-02-21 07:51:19 
2024-02-21 07:51:19 The above exception was the direct cause of the following exception:
2024-02-21 07:51:19 
2024-02-21 07:51:19 Traceback (most recent call last):
2024-02-21 07:51:19   File "<frozen runpy>", line 198, in _run_module_as_main
2024-02-21 07:51:19   File "<frozen runpy>", line 88, in _run_code
2024-02-21 07:51:19   File "/code/src/scripts/create_first_tier.py", line 30, in <module>
2024-02-21 07:51:19     loop.run_until_complete(main())
2024-02-21 07:51:19   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
2024-02-21 07:51:19     return future.result()
2024-02-21 07:51:19            ^^^^^^^^^^^^^^^
2024-02-21 07:51:19   File "/code/src/scripts/create_first_tier.py", line 25, in main
2024-02-21 07:51:19     await create_first_tier(session)
2024-02-21 07:51:19   File "/code/src/scripts/create_first_tier.py", line 14, in create_first_tier
2024-02-21 07:51:19     result = await session.execute(query)

-----------------------------
create_superuser
no logs but container is starting and exiting. is that the expected behaviour?

**Comment by igorbenav** [comment]
Weird. There are actually no logs indeed, but the tier should be created. I'm running it here and it's creating. Can you please share your docker-compose, Dockerfile and the relevant parts of your .env?

**Comment by rithin** [comment]
@igorbenav  you can find it here ->  https://github.com/rithin/kappitrails_api/tree/development_v1

**Comment by igorbenav** [comment]
I think you forgot to uncomment this part in docker-compose:

```
# #   #-------- uncomment to create first tier --------
#   create_tier:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     env_file:
#       - ./src/.env
#     depends_on:
#       - db
#       - web
#     command: python -m src.scripts.create_first_tier
#     volumes:
#       - ./src:/code/src
```

If you want logging, the latest update I merged adds it to the scripts. Just replace the old scripts with the new ones

**Comment by rithin** [comment]
@igorbenav  sorry i didn't push the latest code to git. I enabled and the container got created. But its keep exiting 
![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/aea5be62-3f3f-4b22-8ab6-44202f7fa7b9)

**Comment by igorbenav** [comment]
Weird. Can you please replace the script with the new one and try again so we can see the logs? Run a `docker compose build --no-cache`, then `docker compose up`

**Comment by rithin** [comment]
Same, it's started and exited. 
Logs
2024-02-22 16:57:19 ERROR:__main__:Error creating tier: 
![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/f2e81dc1-a827-4fc1-afb3-298d2cfe9773)
![image](https://github.com/igorbenav/FastAPI-boilerplate/assets/4413553/ce0bc5a0-4d13-4517-8016-ceba301be9c5)

**Comment by igorbenav** [comment]
Yeah, when I remove the `networks` part in docker-compose it works:

```sh
kappitrails_api-development_v1-create_tier-1       | INFO:__main__:Tier 'free' created successfully.
kappitrails_api-development_v1-create_tier-1 exited with code 0
```

So there's something wrong with this setting

**Comment by rithin** [comment]
@igorbenav , thanks for reply.  When I remove the network setting from docker compose am get another error.

File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in lifespan
2024-02-24 11:10:13     async with self.lifespan_context(app) as maybe_state:
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-02-24 11:10:13     return await anext(self.gen)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/code/app/core/setup.py", line 92, in lifespan
2024-02-24 11:10:13     await create_tables()
2024-02-24 11:10:13   File "/code/app/core/setup.py", line 34, in create_tables
2024-02-24 11:10:13     async with engine.begin() as conn:
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-02-24 11:10:13     return await anext(self.gen)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1054, in begin
2024-02-24 11:10:13     async with conn:
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
2024-02-24 11:10:13     return await self.start(is_ctxmanager=True)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
2024-02-24 11:10:13     await greenlet_spawn(self.sync_engine.connect)
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
2024-02-24 11:10:13     result = context.throw(*sys.exc_info())
2024-02-24 11:10:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
2024-02-24 11:10:13     return self._connection_cls(self)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
2024-02-24 11:10:13     self._dbapi_connection = engine.raw_connection()
2024-02-24 11:10:13                              ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
2024-02-24 11:10:13     return self.pool.connect()
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
2024-02-24 11:10:13     return _ConnectionFairy._checkout(self)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
2024-02-24 11:10:13     fairy = _ConnectionRecord.checkout(pool)
2024-02-24 11:10:13             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
2024-02-24 11:10:13     rec = pool._do_get()
2024-02-24 11:10:13           ^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
2024-02-24 11:10:13     with util.safe_reraise():
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
2024-02-24 11:10:13     raise exc_value.with_traceback(exc_tb)
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
2024-02-24 11:10:13     return self._create_connection()
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
2024-02-24 11:10:13     return _ConnectionRecord(self)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
2024-02-24 11:10:13     self.__connect()
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
2024-02-24 11:10:13     with util.safe_reraise():
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
2024-02-24 11:10:13     raise exc_value.with_traceback(exc_tb)
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
2024-02-24 11:10:13     self.dbapi_connection = connection = pool._invoke_creator(self)
2024-02-24 11:10:13                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 643, in connect
2024-02-24 11:10:13     return dialect.connect(*cargs, **cparams)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
2024-02-24 11:10:13     return self.loaded_dbapi.connect(*cargs, **cparams)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
2024-02-24 11:10:13     await_only(creator_fn(*arg, **kw)),
2024-02-24 11:10:13     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
2024-02-24 11:10:13     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
2024-02-24 11:10:13     value = await result
2024-02-24 11:10:13             ^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2329, in connect
2024-02-24 11:10:13     return await connect_utils._connect(
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
2024-02-24 11:10:13     raise last_error or exceptions.TargetServerAttributeNotMatched(
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 991, in _connect
2024-02-24 11:10:13     conn = await _connect_addr(
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
2024-02-24 11:10:13     return await __connect_addr(params, True, *args)
2024-02-24 11:10:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
2024-02-24 11:10:13     tr, pr = await connector
2024-02-24 11:10:13              ^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
2024-02-24 11:10:13     tr, pr = await loop.create_connection(
2024-02-24 11:10:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 11:10:13   File "uvloop/loop.pyx", line 2042, in create_connection
2024-02-24 11:10:13 OSError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Cannot assign requested address
----------------------------
version: '3.8'
# networks:
#   app_net:
#     ipam:
#      config:
#        - subnet: 172.28.0.0/16

services:
  db:
    image: postgres:13
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # -------- replace with comment to run migrations with docker --------
    expose:
      - "5432"
    ports:
     - 5432:5432
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.2
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # -------- replace with comment to run with gunicorn --------
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    env_file:
      - ./src/.env
    # -------- replace with comment if you are using nginx --------
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.3
    # extra_hosts: 
    #   - "db:172.28.0.2"


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.4  

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.5

  #-------- uncomment to run with pgadmin --------
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./src/.env
    depends_on:
      - db
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.6

  #-------- uncomment to run with nginx --------
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web

  #-------- uncomment to create first superuser --------
  create_superuser:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_first_superuser
    volumes:
      - ./src:/code/src
    # networks:
    #  app_net:
    #    ipv4_address: 172.28.0.7 

# #   #-------- uncomment to create first tier --------
  create_tier:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_first_tier
    volumes:
      - ./src:/code/src


# #  #-------- uncomment to run tests --------
#   pytest:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     env_file:
#       - ./src/.env
#     depends_on:
#       - db
#       - create_superuser
#       - redis
#     command: python -m pytest ./tests
#     volumes:
#       - .:/code

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:

**Comment by igorbenav** [comment]
@rithin were you able to fix this? Sorry, I missed the last reply

**Comment by rithin** [comment]
@igorbenav  no, still create_superuser-1 and create_tier-1 not running and trhowing error.


2024-03-10 16:52:06 INFO:__main__:Admin user rithin already exists.
2024-03-17 17:12:47 INFO:__main__:Admin user rithin already exists.
===============
2024-03-10 16:53:05 ERROR:__main__:Error creating tier: 
2024-03-17 17:13:46 ERROR:__main__:Error creating tier:


create_superuser I guess it is a valid error, there is one user called "rithin" already there as a superuser. But surprisingly it's starting and exiting.

**Comment by igorbenav** [comment]
Closing. This is a 2024 issue against `src/app/api/v1/users.py`, which no longer exists. The routing structure was rebuilt in v0.18; routes now live under `backend/src/modules/*/routes.py` and `backend/src/interfaces/api/v1/`. If you can still reproduce a 404 against the current `main`, please open a fresh issue with the failing endpoint.
